onlineedu/src/main/java/cz/cvut/kotyna/onlineedu/jsf/UserBackingBean.java
package cz.cvut.kotyna.onlineedu.jsf;

import cz.cvut.kotyna.onlineedu.entity.Parent;
import cz.cvut.kotyna.onlineedu.entity.Student;
import cz.cvut.kotyna.onlineedu.entity.Teacher;
import cz.cvut.kotyna.onlineedu.entity.UserAccount;
import cz.cvut.kotyna.onlineedu.service.AuthService;
import cz.cvut.kotyna.onlineedu.service.LoginService;
import cz.cvut.kotyna.onlineedu.service.UserService;

import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.io.Serializable;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import java.util.List;

@Named(value = "userBackingBean")
@ViewScoped
public class UserBackingBean implements Serializable {

    @EJB
    private UserService userService;
    @EJB
    private LoginService loginService;

    private String currentPassword;
    private String newPassword;
    private String newPasswordRepeated;

    public List<UserAccount> getAllUsers() {
        return userService.getAllUsers();
    }

    public List<Student> getAllStudents() {
        return userService.getAllStudents();
    }

    public List<Parent> getAllParents() {
        return userService.getAllParents();
    }

    public List<Teacher> getAllTeachers() {
        return userService.getAllTeachers();
    }

    public UserAccount getLoggedInUser() {
        return loginService != null ? loginService.getLoggedInUser() : null;
    }

    public void changePassword(Integer userAccountId) {
        UserAccount userAccount = userService.findUserAccount(userAccountId);
        String currentPasswordHashed = "";
        String newPasswordHashed = "";

        try {
            currentPasswordHashed = AuthService.encodeSHA256(currentPassword, "");
            newPasswordHashed = AuthService.encodeSHA256(newPassword, "");
        } catch (UnsupportedEncodingException | NoSuchAlgorithmException e) {
            e.printStackTrace();
            return;
        }

        if (!currentPasswordHashed.equals(userAccount.getPassword())) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Chybné heslo", "Zadané současné heslo je chybné!"));
        }
        else if (!newPassword.equals(newPasswordRepeated)) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Různá hesla", "Zadaná nová hesla se neshodují!"));
        }
        else {
            userAccount.setPassword(newPasswordHashed);
            userService.saveUserAccount(userAccount);
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Heslo změněno", "Heslo bylo úspěšně změněno!"));
            this.currentPassword = "";
            this.newPassword = "";
            this.newPasswordRepeated = "";
        }
    }


    // Getters & Setters


    public String getCurrentPassword() {
        return currentPassword;
    }

    public void setCurrentPassword(String currentPassword) {
        this.currentPassword = currentPassword;
    }

    public String getNewPassword() {
        return newPassword;
    }

    public void setNewPassword(String newPassword) {
        this.newPassword = newPassword;
    }

    public String getNewPasswordRepeated() {
        return newPasswordRepeated;
    }

    public void setNewPasswordRepeated(String newPasswordRepeated) {
        this.newPasswordRepeated = newPasswordRepeated;
    }
}

onlineedu/src/main/webapp/WEB-INF/templates/admin-template.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:p="http://primefaces.org/ui"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        template="/WEB-INF/templates/template.xhtml">

    <ui:define name="top-nav">
        <ul class="top-nav-list"></ul>
    </ui:define>

    <ui:define name="left-nav">
        <ul>
            <h:messages style="color: red"/>

            <li class="#{urlHelperBean.isCurrentPage('classrooms') ? 'active' : ''}">
                <h:link outcome="/admin/classrooms" value="Třídy"/>
            </li>
            <li class="#{urlHelperBean.isCurrentPage('teachers') ? 'active' : ''}">
                <h:link outcome="/admin/teachers" value="Učitelé"/>
            </li>
            <li class="#{urlHelperBean.isCurrentPage('students') ? 'active' : ''}">
                <h:link outcome="/admin/students" value="Žáci"/>
            </li>
            <li class="#{urlHelperBean.isCurrentPage('admins') ? 'active' : ''}">
                <h:link outcome="/admin/admins" value="Administrátoři"/>
            </li>
            <li class="#{urlHelperBean.isCurrentPage('avatars') ? 'active' : ''}">
                <h:link outcome="/admin/avatars" value="Avataři"/>
            </li>
        </ul>
    </ui:define>

    <ui:define name="top-right-menu">
        <div class="column-narrow flex-column">
            <h:form id="login-form">
                <p:menuButton id="menu-btn" rendered="#{userLogin.loggedIn}" value="#{userBackingBean.loggedInUser.firstname} #{userBackingBean.loggedInUser.surname}">
                    <p:menuitem id="menu-item-profile" outcome="/admin/admins/admin" value="Uživatelský profil" update="messages" icon="pi pi-user">
                        <f:param name="adminId" value="#{userBackingBean.loggedInUser.id}" />
                    </p:menuitem>
                    <p:separator />
                    <p:menuitem id="logoutbtn" value="Odhlásit" action="#{userLogin.logout}" ajax="false" icon="pi pi-sign-out"/>
                </p:menuButton>
                <p:growl id="messages" showDetail="true" skipDetailIfEqualsSummary="true"/>
            </h:form>
        </div>
    </ui:define>


</ui:composition>

onlineedu/src/main/webapp/WEB-INF/templates/student-profile-template.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:p="http://primefaces.org/ui"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        template="/WEB-INF/templates/template.xhtml">

    <ui:define name="top-nav">
        <ul class="top-nav-list"></ul>
    </ui:define>

    <ui:define name="left-nav">
        <ul>
            <h:messages style="color: red"/>

            <li class="#{urlHelperBean.isCurrentPage('home') ? 'active' : ''}">
                <h:link outcome="/student/home" value="Třídní chat" includeViewParams="true"/>
            </li>
            <li class="#{urlHelperBean.isCurrentPage('tasks') ? 'active' : ''}">
                <h:link outcome="/student/tasks" includeViewParams="true" >
                    <h:outputText value="Úkoly" />
                </h:link>
            </li>
            <li class="#{urlHelperBean.isCurrentPage('extra-tasks') ? 'active' : ''}">
                <h:link outcome="/student/extra-tasks" includeViewParams="true" >
                    <h:outputText value="Cvičení za body" />
                </h:link>
            </li>
            <li class="#{urlHelperBean.isCurrentPage('leaderboard') ? 'active' : ''}">
                <h:link outcome="/student/leaderboard" value="Žebříček" includeViewParams="true"/>
            </li>
            <li class="#{urlHelperBean.isCurrentPage('avatars') ? 'active' : ''}">
                <h:link outcome="/student/avatars" value="Avataři" includeViewParams="true"/>
            </li>
        </ul>
    </ui:define>

    <ui:define name="top-right-menu">
        <div class="column-narrow flex-column">
            <h:form id="login-form">
                <div class="p-grid p-ai-center vertical-container">
                    <div class="p-col-12 p-lg-8">
                        <p:menuButton id="menu-btn" rendered="#{userLogin.loggedIn}" value="#{userBackingBean.loggedInUser.firstname} #{userBackingBean.loggedInUser.surname}">
                            <p:menuitem id="menu-item-profile" outcome="/student/user" value="Uživatelský profil" update="messages" icon="pi pi-user">
                                <f:param name="userAccountId" value="#{userBackingBean.loggedInUser.id}" />
                            </p:menuitem>
                            <p:separator />
                            <p:menuitem id="logoutbtn" value="Odhlásit" action="#{userLogin.logout}" ajax="false" icon="pi pi-sign-out"/>
                        </p:menuButton>
                    </div>
                    <div class="p-col-12 p-lg-4">
                        <p:graphicImage cache="false" id="top-nav-user-profile-avatar" value="/avatars/user/#{userBackingBean.loggedInUser.id}" style="max-height: 2.5rem;max-width: 2.5rem;"/>
                    </div>
                </div>
                <p:growl id="messages" showDetail="true" skipDetailIfEqualsSummary="true"/>
            </h:form>
        </div>
    </ui:define>

</ui:composition>

onlineedu/src/main/webapp/WEB-INF/templates/student-template.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:p="http://primefaces.org/ui"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        template="/WEB-INF/templates/template.xhtml">

    <ui:define name="top-nav">
        <ul class="top-nav-list">
            <ui:repeat value="#{userBackingBean.loggedInUser.student.classroom.teachingCollection}" var="teaching">
                <li class="#{studentTeachingBean.isCurrentTeaching(teaching.id.toString()) ? 'active' : ''}">
                    <h:link>
                        <h:outputText value="#{teaching.subject.name}" />
                        <h:outputText value=" (#{studentTeachingBean.getNumberOfTasksInNewOrReturnedStateForRhsTeaching(teaching.id)})" />
                        <f:param name="teachingId" value="#{teaching.id}" />
                    </h:link>
                </li>
            </ui:repeat>
        </ul>
    </ui:define>

    <ui:define name="left-nav">
        <ul>
            <h:messages style="color: red"/>

            <li class="#{urlHelperBean.isCurrentPage('home') ? 'active' : ''}">
                <h:link outcome="/student/home" value="Třídní chat" includeViewParams="true"/>
            </li>
            <li class="#{urlHelperBean.isCurrentPage('tasks') ? 'active' : ''}">
                <h:link outcome="/student/tasks" includeViewParams="true" >
                    <h:outputText value="Úkoly (#{studentTeachingBean.getNumberOfTasksInNewOrReturnedStateForRhsType('normal')})" />
                </h:link>
            </li>
            <li class="#{urlHelperBean.isCurrentPage('extra-tasks') ? 'active' : ''}">
                <h:link outcome="/student/extra-tasks" includeViewParams="true" >
                    <h:outputText value="Cvičení za body (#{studentTeachingBean.getNumberOfTasksInNewOrReturnedStateForRhsType('extra')})" />
                </h:link>
            </li>
            <li class="#{urlHelperBean.isCurrentPage('leaderboard') ? 'active' : ''}">
                <h:link outcome="/student/leaderboard" value="Žebříček" includeViewParams="true"/>
            </li>
            <li class="#{urlHelperBean.isCurrentPage('avatars') ? 'active' : ''}">
                <h:link outcome="/student/avatars" value="Avataři" includeViewParams="true"/>
            </li>
        </ul>
    </ui:define>

    <ui:define name="top-right-menu">
        <div class="column-narrow flex-column">
            <h:form id="login-form">
                <div class="p-grid p-ai-center vertical-container">
                    <div class="p-col-12 p-lg-8">
                        <p:menuButton id="menu-btn" rendered="#{userLogin.loggedIn}" value="#{userBackingBean.loggedInUser.firstname} #{userBackingBean.loggedInUser.surname}">
                            <p:menuitem id="menu-item-profile" outcome="/student/user" value="Uživatelský profil" update="messages" icon="pi pi-user">
                                <f:param name="userAccountId" value="#{userBackingBean.loggedInUser.id}" />
                                <f:param name="teachingId" value="#{studentTeachingBean.teachingId}" />
                            </p:menuitem>
                            <p:separator />
                            <p:menuitem id="logoutbtn" value="Odhlásit" action="#{userLogin.logout}" ajax="false" icon="pi pi-sign-out"/>
                        </p:menuButton>
                    </div>
                    <div class="p-col-12 p-lg-4">
                        <p:graphicImage cache="false" id="top-nav-user-profile-avatar" value="/avatars/user/#{userBackingBean.loggedInUser.id}" style="max-height: 2.5rem;max-width: 2.5rem;"/>
                    </div>
                </div>
              <p:growl id="messages" showDetail="true" skipDetailIfEqualsSummary="true"/>
            </h:form>

        </div>
    </ui:define>

</ui:composition>

onlineedu/src/main/webapp/WEB-INF/templates/teacher-profile-template.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:p="http://primefaces.org/ui"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        template="/WEB-INF/templates/template.xhtml">

    <ui:define name="top-nav">
        <ul class="top-nav-list"></ul>
    </ui:define>

    <ui:define name="left-nav">
        <ul>
            <h:messages style="color: red"/>

            <li class="#{urlHelperBean.isCurrentPage('home') ? 'active' : ''}">
                <h:link outcome="/teacher/home" value="Třídní chat" includeViewParams="true"/>
            </li>
            <li class="#{urlHelperBean.isCurrentPage('tasks') ? 'active' : ''}">
                <h:link outcome="/teacher/tasks" value="Úkoly" includeViewParams="true" />
            </li>
            <li class="#{urlHelperBean.isCurrentPage('extra-tasks') ? 'active' : ''}">
                <h:link outcome="/teacher/extra-tasks" value="Cvičení za body" includeViewParams="true" />
            </li>
            <li class="#{urlHelperBean.isCurrentPage('students') ? 'active' : ''}">
                <h:link outcome="/teacher/students" value="Seznam žáků" includeViewParams="true" />
            </li>
            <li class="#{urlHelperBean.isCurrentPage('classbook') ? 'active' : ''}">
                <h:link outcome="/teacher/classbook" value="Třídní kniha" includeViewParams="true" />
            </li>
            <li class="#{urlHelperBean.isCurrentPage('news') ? 'active' : ''}">
                <h:link outcome="/teacher/news" value="Novinky" includeViewParams="true" />
            </li>

        </ul>
    </ui:define>

    <ui:define name="top-right-menu">
        <div class="column-narrow flex-column">
            <h:form id="login-form">
                <p:menuButton id="menu-btn" rendered="#{userLogin.loggedIn}" value="#{userBackingBean.loggedInUser.firstname} #{userBackingBean.loggedInUser.surname}">
                    <p:menuitem id="menu-item-profile" outcome="/teacher/user" value="Uživatelský profil" update="messages" icon="pi pi-user">
                        <f:param name="userAccountId" value="#{userBackingBean.loggedInUser.id}" />
                    </p:menuitem>
                    <p:separator />
                    <p:menuitem id="logoutbtn" value="Odhlásit" action="#{userLogin.logout}" ajax="false" icon="pi pi-sign-out"/>
                </p:menuButton>
                <p:growl id="messages" showDetail="true" skipDetailIfEqualsSummary="true"/>
            </h:form>
        </div>
    </ui:define>


</ui:composition>

onlineedu/src/main/webapp/WEB-INF/templates/teacher-template.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:p="http://primefaces.org/ui"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        template="/WEB-INF/templates/template.xhtml">

    <ui:define name="top-nav">
        <div class="top-nav-list-wrapper">
            <div class="top-nav-list-column">
                <ul class="top-nav-list-row">
                    <ui:repeat value="#{teacherUserBackingBean.classroomsTeachedByCurrentTeacher}" var="classroom">
                        <li class="#{teacherUserBackingBean.isCurrentClassroom(classroom.id.toString()) ? 'active' : ''}">
                            <h:link>
                                <h:outputText value="#{classroom.name}" />
                                <h:outputText value=" (#{teacherTeachingBean.getNumberOfStudentsThatHaveSomeTaskInSubmittedOrResubmittedStateForRhsClassroom(classroom.id)})" />
                                <f:param name="classroomId" value="#{classroom.id}" />
                            </h:link>
                        </li>
                    </ui:repeat>
                </ul>

                <ul class="top-nav-list-row">
                    <ui:repeat value="#{teacherUserBackingBean.teachersTeachingsInCurrentClassroom}" var="teaching">
                        <li class="#{teacherTeachingBean.isCurrentTeaching(teaching.id.toString()) ? 'active' : ''}">
                            <h:link>
                                <h:outputText value="#{teaching.subject.name}" />
                                <h:outputText value=" (#{teacherTeachingBean.getNumberOfStudentsThatHaveSomeTaskInSubmittedOrResubmittedStateForRhsTeaching(teaching.id)})" />
                                <f:param name="teachingId" value="#{teaching.id}" />
                                <f:param name="studentId" value="#{teacherStudentBean.studentId}" disable="#{empty teacherStudentBean.studentId}" />
                            </h:link>
                        </li>
                    </ui:repeat>
                </ul>
            </div>

        </div>
    </ui:define>

    <ui:define name="left-nav">
        <ul>
            <h:messages style="color: red"/>

            <li class="#{urlHelperBean.isCurrentPage('home') ? 'active' : ''}">
                <h:link outcome="/teacher/home" value="Třídní chat" includeViewParams="true"/>
            </li>
            <li class="#{urlHelperBean.isCurrentPage('tasks') ? 'active' : ''}">
                <h:link outcome="/teacher/tasks" value="Úkoly (#{teacherTeachingBean.getNumberOfStudentsThatHaveSomeTaskInSubmittedOrResubmittedStateForRhsType('normal')})" includeViewParams="true" />
            </li>
            <li class="#{urlHelperBean.isCurrentPage('extra-tasks') ? 'active' : ''}">
                <h:link outcome="/teacher/extra-tasks" value="Cvičení za body (#{teacherTeachingBean.getNumberOfStudentsThatHaveSomeTaskInSubmittedOrResubmittedStateForRhsType('extra')})" includeViewParams="true" />
            </li>
            <li class="#{urlHelperBean.isCurrentPage('students') ? 'active' : ''}">
                <h:link outcome="/teacher/students" value="Seznam žáků" includeViewParams="true" />
            </li>
            <li class="#{urlHelperBean.isCurrentPage('classbook') ? 'active' : ''}">
                <h:link outcome="/teacher/classbook" value="Třídní kniha" includeViewParams="true" />
            </li>
            <li class="#{urlHelperBean.isCurrentPage('news') ? 'active' : ''}">
                <h:link outcome="/teacher/news" value="Novinky (#{teacherTeachingBean.getNumberOfStudentsThatHaveSomeTaskInSubmittedOrResubmittedStateForRhsTeaching(teacherTeachingBean.teaching.id)})" includeViewParams="true" />
            </li>

        </ul>
    </ui:define>

    <ui:define name="top-right-menu">
        <div class="column-narrow flex-column">
            <h:form id="login-form">
                <p:menuButton id="menu-btn" rendered="#{userLogin.loggedIn}" value="#{userBackingBean.loggedInUser.firstname} #{userBackingBean.loggedInUser.surname}">
                    <p:menuitem id="menu-item-profile" outcome="/teacher/user" value="Uživatelský profil" update="messages" icon="pi pi-user">
                        <f:param name="userAccountId" value="#{userBackingBean.loggedInUser.id}" />
                        <f:param name="teachingId" value="#{teacherTeachingBean.teachingId}" />
                        <f:param name="classroomId" value="#{teacherUserBackingBean.classroomId}" />
                    </p:menuitem>
                    <p:separator />
                    <p:menuitem id="logoutbtn" value="Odhlásit" action="#{userLogin.logout}" ajax="false" icon="pi pi-sign-out"/>
                </p:menuButton>
                <p:growl id="messages" showDetail="true" skipDetailIfEqualsSummary="true"/>
            </h:form>
        </div>
    </ui:define>


</ui:composition>

onlineedu/src/main/webapp/WEB-INF/templates/template.xhtml
<!DOCTYPE html>
<html lang="en"
      xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

<ui:insert name="metadata" />

<h:head>
    <title><ui:insert name="title">Online edu</ui:insert></title>
    <h:outputStylesheet name="styles/styles.css" />
    <h:outputStylesheet name="styles/colors.css" />
    <h:outputStylesheet name="styles/primeflex.css" />
    <h:outputStylesheet name="primeicons/primeicons.css" library="primefaces" />
    <h:outputStylesheet library="webjars" name="font-awesome/5.15.2/css/all.min-jsf.css" />
    <h:outputStylesheet library="webjars" name="font-awesome/5.15.2/css/v4-shims.min-jsf.css" />
    <h:outputScript library="js" name="date-picker-locale.js" />
</h:head>

<h:body>
    <f:view>

        <div id="page-wrapper">
            <header>
                <div class="column-narrow">
                    <h:link outcome="/home">
                        <h:graphicImage name="images/logo.jpg" alt="logo" />
                    </h:link>
                </div>
                <ui:insert name="top-nav">
                    <ul class="top-nav-list">
                        <ui:fragment rendered="#{userLogin.loggedIn}">
                            <li>
                                <h:link rendered="#{userBackingBean.loggedInUser.role.equals('student')}" outcome="/student/home" value="Třída">
                                    <f:param name="teachingId" value="#{studentTeachingBean.defaultStudentTeaching.id}" />
                                </h:link>
                                <h:link rendered="#{userBackingBean.loggedInUser.role.equals('teacher')}" outcome="/teacher/home" value="Třída" />
                                <h:link rendered="#{userBackingBean.loggedInUser.role.equals('parent')}" outcome="/parent/home" value="Třída"></h:link>
                                <h:link rendered="#{userBackingBean.loggedInUser.role.equals('admin')}" outcome="/admin/classrooms" value="Admin page"></h:link>
                            </li>
                        </ui:fragment>
                    </ul>
                </ui:insert>
                <ui:insert name="top-right-menu">
                    <div class="column-narrow flex-column">
                        <h:form id="login-form">
                            <p:menuButton id="menu-btn" rendered="#{userLogin.loggedIn}" value="#{userBackingBean.loggedInUser.firstname} #{userBackingBean.loggedInUser.surname}">
                                <p:menuitem id="menu-item-profile" value="Uživatelský profil" update="messages" icon="pi pi-user"/>
                                <p:separator />
                                <p:menuitem id="logoutbtn" value="Odhlásit" action="#{userLogin.logout}" ajax="false" icon="pi pi-sign-out"/>
                            </p:menuButton>
                            <p:growl id="messages" showDetail="true" skipDetailIfEqualsSummary="true"/>
                        </h:form>
                    </div>
                </ui:insert>

            </header>
            <section class="row">
                <aside class="big">
                    <ui:insert name="left-nav">
                    </ui:insert>
                </aside>
                <main class="big"><ui:insert name="content">Default content</ui:insert></main>
                <aside class="big"></aside>
            </section>
            <footer>
                <p>Vytvořeno pro studijní účely.</p>
            </footer>
        </div>

        <h:outputScript library="js" name="close-dialogs-on-click-outside.js" />

    </f:view>
</h:body>
</html>