onlineedu/src/main/java/cz/cvut/kotyna/onlineedu/entity/UserAccount.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.cvut.kotyna.onlineedu.entity;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import cz.cvut.fel.tests.entity.UserInOrganization;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;
import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;

/**
 *
 * @author daniel
 */
@Entity
@Table(name = "user_account")
@NamedQueries({
        @NamedQuery(name = UserAccount.FIND_ALL, query = "SELECT u FROM UserAccount u"),
        @NamedQuery(name = "UserAccount.findById", query = "SELECT u FROM UserAccount u WHERE u.id = :id"),
        @NamedQuery(name = "UserAccount.findByRole", query = "SELECT u FROM UserAccount u WHERE u.role = :role"),
        @NamedQuery(name = "UserAccount.findByUsername", query = "SELECT u FROM UserAccount u WHERE u.username = :username"),
        @NamedQuery(name = "UserAccount.findByPassword", query = "SELECT u FROM UserAccount u WHERE u.password = :password"),
        @NamedQuery(name = "UserAccount.findByEmail", query = "SELECT u FROM UserAccount u WHERE u.email = :email"),
        @NamedQuery(name = "UserAccount.findByFirstname", query = "SELECT u FROM UserAccount u WHERE u.firstname = :firstname"),
        @NamedQuery(name = "UserAccount.findBySurname", query = "SELECT u FROM UserAccount u WHERE u.surname = :surname"),
        @NamedQuery(name = "UserAccount.findByBirthday", query = "SELECT u FROM UserAccount u WHERE u.birthday = :birthday"),
        @NamedQuery(name = "UserAccount.findByRegistered", query = "SELECT u FROM UserAccount u WHERE u.registered = :registered"),
        @NamedQuery(name = "UserAccount.findByStreet", query = "SELECT u FROM UserAccount u WHERE u.street = :street"),
        @NamedQuery(name = "UserAccount.findByZip", query = "SELECT u FROM UserAccount u WHERE u.zip = :zip"),
        @NamedQuery(name = "UserAccount.findByPhone", query = "SELECT u FROM UserAccount u WHERE u.phone = :phone"),
        @NamedQuery(name = UserAccount.FIND_USER_ACCOUNT_BY_USERNAME, query = "select userAccount from UserAccount userAccount where userAccount.username = :username")})
@JsonIdentityInfo(generator= ObjectIdGenerators.PropertyGenerator.class, property="id")
public class UserAccount implements Serializable {

    public static final String FIND_ALL = "UserAccount.findAll";
    public static final String FIND_USER_ACCOUNT_BY_USERNAME = "UserAccount.findUserAccountByUsername";

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id")
    private Integer id;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 64)
    @Column(name = "role")
    private String role;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "username")
    private String username;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 2147483647)
    @Column(name = "password")
    private String password;
    // @Pattern(regexp="[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?", message="Invalid email")//if the field contains email address consider using this annotation to enforce field validation
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "email")
    private String email;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "firstname")
    private String firstname;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "surname")
    private String surname;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 32)
    @Column(name = "gender")
    private String gender;
    @Column(name = "birthday")
    private Date birthday;
    @Column(name = "registered")
    @Temporal(TemporalType.TIMESTAMP)
    private Date registered;
    @Size(max = 128)
    @Column(name = "street")
    private String street;
    @Size(max = 32)
    @Column(name = "zip")
    private String zip;
    @Size(max = 128)
    @Column(name = "city")
    private String city;
    // @Pattern(regexp="^\\(?(\\d{3})\\)?[- ]?(\\d{3})[- ]?(\\d{4})$", message="Invalid phone/fax format, should be as xxx-xxx-xxxx")//if the field contains phone or fax number consider using this annotation to enforce field validation
    @Size(max = 64)
    @Column(name = "phone")
    private String phone;

    @OneToMany(mappedBy = "user_account")
    private List<UserInOrganization> userInOrganizations;

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "userAccount")
    private Collection<Message> messageCollection;
    @OneToOne(cascade = CascadeType.ALL, mappedBy = "userAccount")
    private Parent parent;
    @OneToOne(cascade = CascadeType.ALL, mappedBy = "userAccount")
    private Student student;
    @OneToOne(cascade = CascadeType.ALL, mappedBy = "userAccount")
    private Teacher teacher;
    @OneToMany(mappedBy = "userAccount", cascade = CascadeType.ALL)
    private Collection<UsersAvatar> usersAvatars;

    public UserAccount() {
    }

    public UserAccount(Integer id) {
        this.id = id;
    }

    public UserAccount(Integer id, String role, String username, String password, String email, String firstname, String surname) {
        this.id = id;
        this.role = role;
        this.username = username;
        this.password = password;
        this.email = email;
        this.firstname = firstname;
        this.surname = surname;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public Integer getAge() {
        if (birthday == null) return null;
        LocalDate localDateBirthday = LocalDate.ofInstant(birthday.toInstant(), ZoneId.systemDefault());
        return Period.between(localDateBirthday, LocalDate.now()).getYears();
    }

    public Date getBirthday() {
        return birthday;
    }

    public String getBirthdayFormatted() {
        SimpleDateFormat nf = new SimpleDateFormat("dd. MM. yyyy");
        if (birthday != null) {
            return nf.format(birthday);
        }
        else {
            return "";
        }
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public Date getRegistered() {
        return registered;
    }

    public String getRegisteredFormatted() {
        SimpleDateFormat nf = new SimpleDateFormat("dd. MM. yyyy HH:mm");
        if (registered != null) {
            return nf.format(registered);
        }
        else {
            return "";
        }
    }

    public void setRegistered(Date registered) {
        this.registered = registered;
    }

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getZip() {
        return zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @XmlTransient
    public Collection<Message> getMessageCollection() {
        return messageCollection;
    }

    public void setMessageCollection(Collection<Message> messageCollection) {
        this.messageCollection = messageCollection;
    }

    public Parent getParent() {
        return parent;
    }

    public void setParent(Parent parent) {
        this.parent = parent;
    }

    public Student getStudent() {
        return student;
    }

    public void setStudent(Student student) {
        this.student = student;
    }

    public Teacher getTeacher() {
        return teacher;
    }

    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getGender() {
        return gender;
    }

    public String getGenderFormatted() {
        switch (gender) {

onlineedu/src/main/java/cz/cvut/kotyna/onlineedu/jsf/StudentBean.java
package cz.cvut.kotyna.onlineedu.jsf;

import cz.cvut.kotyna.onlineedu.entity.Student;
import cz.cvut.kotyna.onlineedu.entity.Summary;
import cz.cvut.kotyna.onlineedu.entity.UserAccount;
import cz.cvut.kotyna.onlineedu.service.StudentService;
import cz.cvut.kotyna.onlineedu.service.SummaryService;
import cz.cvut.kotyna.onlineedu.service.TeachingService;
import cz.cvut.kotyna.onlineedu.service.UserService;
import org.primefaces.PrimeFaces;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Optional;

public class StudentBean {

    @EJB
    protected StudentService studentService;
    @EJB
    protected UserService userService;
    @EJB
    protected TeachingService teachingService;

    protected List<Student> allStudents;
    protected Student student;
    protected Integer studentId;

    @PostConstruct
    public void init() {
        allStudents = new ArrayList<>(studentService.getAllStudents());
        student = new Student();
        student.setUserAccount(new UserAccount());
    }

    public void initStudent() {
        student = studentService.findStudent(studentId);
    }

    public void initNewStudent() {
        student = new Student();
        student.setUserAccount(new UserAccount());
    }

    public void saveStudent() {
        if (student.getId() == null) {
            student.getUserAccount().setRole("student");
            student.getUserAccount().setRegistered(new Date());
            // generate username and hashed password (same as username for testing purposes)
            student.setUserAccount(userService.generateUserAccountUsernameAndPassword(student.getUserAccount()));
            studentService.saveStudent(student);
            // reload student
            student = studentService.findStudent(student.getId());

            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Student vytvořen"));
        }
        else {
            studentService.saveStudent(student);
            // reload student
            student = studentService.findStudent(student.getId());

            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Student upraven"));
        }
    }

    public Summary getStudentSummaryForRhsTeaching(Integer teachingId) {
        if (student == null) return null;
        Optional<Summary> s = student.getSummaryCollection().stream().filter(x -> x.getTeaching().getId().equals(teachingId)).findFirst();
        if (s.isPresent()) {
            return s.get();
        }
        Summary summary = new Summary();
        summary.setStudent(student);
        summary.setTeaching(teachingService.findTeaching(teachingId));
        summary.setFeedback("");
        summary.setFinalGrade("");
        student.getSummaryCollection().add(summary);
        return summary;
    }

    // Getters & Setters


    public List<Student> getAllStudents() {
        return allStudents;
    }

    public void setAllStudents(List<Student> allStudents) {
        this.allStudents = allStudents;
    }

    public Student getStudent() {
        return student;
    }

    public void setStudent(Student student) {
        this.student = student;
    }

    public Integer getStudentId() {
        return studentId;
    }

    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }
}

onlineedu/src/main/java/cz/cvut/kotyna/onlineedu/jsf/UserBackingBean.java
package cz.cvut.kotyna.onlineedu.jsf;

import cz.cvut.kotyna.onlineedu.entity.Parent;
import cz.cvut.kotyna.onlineedu.entity.Student;
import cz.cvut.kotyna.onlineedu.entity.Teacher;
import cz.cvut.kotyna.onlineedu.entity.UserAccount;
import cz.cvut.kotyna.onlineedu.service.AuthService;
import cz.cvut.kotyna.onlineedu.service.LoginService;
import cz.cvut.kotyna.onlineedu.service.UserService;

import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.io.Serializable;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import java.util.List;

@Named(value = "userBackingBean")
@ViewScoped
public class UserBackingBean implements Serializable {

    @EJB
    private UserService userService;
    @EJB
    private LoginService loginService;

    private String currentPassword;
    private String newPassword;
    private String newPasswordRepeated;

    public List<UserAccount> getAllUsers() {
        return userService.getAllUsers();
    }

    public List<Student> getAllStudents() {
        return userService.getAllStudents();
    }

    public List<Parent> getAllParents() {
        return userService.getAllParents();
    }

    public List<Teacher> getAllTeachers() {
        return userService.getAllTeachers();
    }

    public UserAccount getLoggedInUser() {
        return loginService != null ? loginService.getLoggedInUser() : null;
    }

    public void changePassword(Integer userAccountId) {
        UserAccount userAccount = userService.findUserAccount(userAccountId);
        String currentPasswordHashed = "";
        String newPasswordHashed = "";

        try {
            currentPasswordHashed = AuthService.encodeSHA256(currentPassword, "");
            newPasswordHashed = AuthService.encodeSHA256(newPassword, "");
        } catch (UnsupportedEncodingException | NoSuchAlgorithmException e) {
            e.printStackTrace();
            return;
        }

        if (!currentPasswordHashed.equals(userAccount.getPassword())) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Chybné heslo", "Zadané současné heslo je chybné!"));
        }
        else if (!newPassword.equals(newPasswordRepeated)) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Různá hesla", "Zadaná nová hesla se neshodují!"));
        }
        else {
            userAccount.setPassword(newPasswordHashed);
            userService.saveUserAccount(userAccount);
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Heslo změněno", "Heslo bylo úspěšně změněno!"));
            this.currentPassword = "";
            this.newPassword = "";
            this.newPasswordRepeated = "";
        }
    }


    // Getters & Setters


    public String getCurrentPassword() {
        return currentPassword;
    }

    public void setCurrentPassword(String currentPassword) {
        this.currentPassword = currentPassword;
    }

    public String getNewPassword() {
        return newPassword;
    }

    public void setNewPassword(String newPassword) {
        this.newPassword = newPassword;
    }

    public String getNewPasswordRepeated() {
        return newPasswordRepeated;
    }

    public void setNewPasswordRepeated(String newPasswordRepeated) {
        this.newPasswordRepeated = newPasswordRepeated;
    }
}

onlineedu/src/main/webapp/admin/teachers.xhtml
<ui:composition template="/WEB-INF/templates/admin-template.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">

    <ui:define name="title">
        Admin - seznam učitelů
    </ui:define>

    <ui:define name="content">
        <h1>Učitelé</h1>

        <h:form id="form">

            <p:growl id="messages" showDetail="true" skipDetailIfEqualsSummary="true" />

            <p:dataTable id="dt-teachers" var="teacher" value="#{userBackingBean.allTeachers}" size="small">

                <f:facet name="header">
                    <div class="buttonbar">
                        <div>
                            <p:commandButton id="btn-add-teacher" value="Přidat" icon="pi pi-plus" actionListener="#{adminTeacherBean.initNewTeacher}"
                                             update=":form:manage-teacher-content" oncomplete="PF('manageTeacherDialog').show()"
                                             styleClass="ui-button-success" style="margin-right: .5rem">
                                <p:resetInput target=":form:manage-teacher-content"/>
                            </p:commandButton>
                        </div>
                        <div>
                            <p:commandButton id="toggler" type="button" value="Vybrat sloupce" icon="pi pi-align-justify" />
                            <p:columnToggler datasource="dt-teachers" trigger="toggler" />
                        </div>
                    </div>
                </f:facet>

                <p:column headerText="Username" sortBy="#{teacher.userAccount.username}">
                    <h:outputText value="#{teacher.userAccount.username}" />
                </p:column>

                <p:column headerText="Jméno a příjmení" sortBy="#{teacher.userAccount.firstname} #{teacher.userAccount.surname}">
                    <h:outputText value="#{teacher.userAccount.firstname} #{teacher.userAccount.surname}" />
                </p:column>

                <p:column headerText="Pohlaví" visible="false">
                    <h:outputText value="#{teacher.userAccount.genderFormatted}" />
                </p:column>

                <p:column headerText="Email" sortBy="#{teacher.userAccount.email}">
                    <h:outputText value="#{teacher.userAccount.email}" />
                </p:column>

                <p:column headerText="Mobil" sortBy="#{teacher.userAccount.phone}">
                    <h:outputText value="#{teacher.userAccount.phone}" />
                </p:column>

                <p:column headerText="Adresa" sortBy="#{teacher.userAccount.fullAddress}">
                    <h:outputText value="#{teacher.userAccount.fullAddress}" />
                </p:column>

                <p:column headerText="Datum registrace" sortBy="#{teacher.userAccount.registeredFormatted}" visible="false">
                    <h:outputText value="#{teacher.userAccount.registeredFormatted}" />
                </p:column>

                <p:column headerText="Datum narození" sortBy="#{teacher.userAccount.birthdayFormatted}" visible="false">
                    <h:outputText value="#{teacher.userAccount.birthdayFormatted}" />
                </p:column>

                <p:column headerText="Třída" sortBy="#{teacher.classroom.name}">
                    <h:outputText value="#{teacher.classroom.name}" />
                </p:column>

                <p:column style="width:5rem;text-align: center" exportable="false">

                    <p:commandButton id="btn-teacher-edit-#{teacher.id}" icon="pi pi-pencil" update=":form:manage-teacher-content"
                                     oncomplete="PF('manageTeacherDialog').show()"
                                     styleClass="ui-button-success" style="margin-right: 0.25rem;" process="@this">
                        <f:setPropertyActionListener value="#{teacher}" target="#{adminTeacherBean.teacher}"/>
                        <p:resetInput target=":form:manage-teacher-content"/>
                    </p:commandButton>

                    <p:linkButton id="btn-teacher-detail-#{teacher.id}" outcome="/admin/teachers/teacher" icon="pi pi-search" title="Detail">
                        <f:param name="teacherId" value="#{teacher.id}" />
                    </p:linkButton>

                </p:column>

            </p:dataTable>


            <p:dialog header="Nový učitel" width="450" showEffect="fade" modal="true"
                      widgetVar="manageTeacherDialog" responsive="true" style="max-height: 90%;overflow-y: auto;">
                <p:outputPanel id="manage-teacher-content" class="ui-fluid">
                    <div class="p-field">
                        <p:outputLabel for="firstname">Jméno</p:outputLabel>
                        <p:inputText id="firstname" value="#{adminTeacherBean.teacher.userAccount.firstname}" required="true" requiredMessage="Jméno je povinné pole"/>
                    </div>
                    <div class="p-field">
                        <p:outputLabel for="surname">Příjmení</p:outputLabel>
                        <p:inputText id="surname" value="#{adminTeacherBean.teacher.userAccount.surname}" required="true" requiredMessage="Příjmení je povinné pole"/>
                    </div>

                    <div class="p-field">
                        <p:outputLabel for="gender">Pohlaví</p:outputLabel>
                        <p:selectOneMenu id="gender" value="#{adminTeacherBean.teacher.userAccount.gender}" layout="responsive" required="true" requiredMessage="Pohlaví je povinné pole">
                            <f:selectItem itemValue="#{null}" itemLabel="-- zvolit --" />
                            <f:selectItem itemValue="male" itemLabel="Muž" />
                            <f:selectItem itemValue="female" itemLabel="Žena" />
                        </p:selectOneMenu>
                    </div>

                    <div class="p-field">
                        <p:outputLabel for="phone">Telefon</p:outputLabel>
                        <p:inputText id="phone" value="#{adminTeacherBean.teacher.userAccount.phone}" required="true" requiredMessage="Telefon je povinné pole"/>
                    </div>
                    <div class="p-field">
                        <p:outputLabel for="email">Email</p:outputLabel>
                        <p:inputText id="email" value="#{adminTeacherBean.teacher.userAccount.email}" required="true" requiredMessage="Email je povinné pole"/>
                    </div>
                    <div class="p-field">
                        <p:outputLabel for="street">Ulice</p:outputLabel>
                        <p:inputText id="street" value="#{adminTeacherBean.teacher.userAccount.street}"/>
                    </div>
                    <div class="p-field">
                        <p:outputLabel for="zip">PSČ</p:outputLabel>
                        <p:inputText id="zip" value="#{adminTeacherBean.teacher.userAccount.zip}"/>
                    </div>
                    <div class="p-field">
                        <p:outputLabel for="city">Město</p:outputLabel>
                        <p:inputText id="city" value="#{adminTeacherBean.teacher.userAccount.city}"/>
                    </div>
                    <div class="p-field">
                        <p:outputLabel for="birthday">Datum narození</p:outputLabel>
                        <p:datePicker id="birthday" value="#{adminTeacherBean.teacher.userAccount.birthday}" monthNavigator="true" yearNavigator="true" locale="cs" pattern="dd.MM.yyyy"/>
                    </div>

                    <div class="p-field">
                        <p:outputLabel for="classroom">Třída</p:outputLabel>
                        <p:selectOneMenu id="classroom" value="#{adminTeacherBean.teacher.classroom}" layout="responsive" converter="omnifaces.SelectItemsConverter">
                            <f:selectItem itemValue="#{null}" itemLabel="-- zvolit --" />
                            <f:selectItems value="#{adminClassroomBean.classroomsWithoutTeacher}" var="classroom" itemValue="#{classroom}" itemLabel="#{classroom.name}" />
                        </p:selectOneMenu>
                    </div>

                </p:outputPanel>

                <f:facet name="footer">
                    <p:defaultCommand target="save-command-button"/>
                    <p:commandButton id="save-command-button" value="Uložit" icon="pi pi-check" actionListener="#{adminTeacherBean.saveTeacher}"
                                     update="manage-teacher-content dt-teachers messages" process="manage-teacher-content @this"/>
                    <p:commandButton value="Zrušit" icon="pi pi-times" onclick="PF('manageTeacherDialog').hide()"
                                     class="ui-button-secondary" update="manage-teacher-content" process="@this" >
                        <p:resetInput target="manage-teacher-content"/>
                    </p:commandButton>
                </f:facet>

            </p:dialog>


        </h:form>



    </ui:define>
</ui:composition>